name: TruePlugin
version: '${project.version}'
main: fr.levraigabin.trueplugin.TruePlugin
api-version: 1.19
authors: [ LeVraiGabin ]
description: Minecraft But and Scenarios for Youtube Videos
website: https://youtube.com/c/LeVraiGabin
commands:
  trueplugin:
    description: TruePlugin main command
    aliases:
      - trp